// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnOC1uYKHbS2hX5nJ0Aa3F0K9FEEM4pHM',
    appId: '1:321686830330:android:fba34125eb2dbac3cc9d43',
    messagingSenderId: '321686830330',
    projectId: 'flutterinstargram',
    storageBucket: 'flutterinstargram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT6bvLMvzdrgWFRKuLyBS2X5I97tZsOhg',
    appId: '1:321686830330:ios:9477f9851dd2bc68cc9d43',
    messagingSenderId: '321686830330',
    projectId: 'flutterinstargram',
    storageBucket: 'flutterinstargram.appspot.com',
    iosClientId: '321686830330-0rf4h1bdulofcgaaqmt6m6rt6gma2kt6.apps.googleusercontent.com',
    iosBundleId: 'com.park.instargram',
  );
}
